### ISSUE TITLE
Empty passwords forbidden

### ISSUE THREAD

**Issue by thesourcerer8** [edwig/ODBCQueryTool#2]
ODBCQueryTool 2.2.0 Build 206 does not allow to connect to a database with a username and an empty password. This is a showstopper for me.

**Comment by edwig** [comment]
Hi thesourcerer8,

 

Of course I can build in an option to log in without a password.

But please can you give me more information on this request?

Is it for a special kind of database? 

Can I test it with that database?

Is a (non-effective) username OK, or is it a datasource that has no username either?

 

A bit more information on this request would be nice.

 

Yours truly,

 

Edwig Huisman

 

Van: thesourcerer8 [mailto:notifications@github.com] 
Verzonden: woensdag 23 augustus 2017 14:49
Aan: edwig/ODBCQueryTool <ODBCQueryTool@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [edwig/ODBCQueryTool] Empty passwords forbidden (#2)

 

ODBCQueryTool 2.2.0 Build 206 does not allow to connect to a database with a username and an empty password. This is a showstopper for me.

**Comment by thesourcerer8** [comment]
I think you just have to remove the error message that comes when an empty password is used, or change the if statement behind it so that it only requires a connection string and a username, and does not care about empty passwords.
The database I am testing it is 4D, which comes with a "User" account with an empty password by default. Yes, you can get free evaluation versions of 4D.
I haven't seen a out-of-process database with an empty username lately, but for things like SQLite perhaps even a username is too much.
Thanks a lot!

**Comment by edwig** [comment]
Hi thesourcerer8

 

Created a 2.2.1 version without the mandatory need for a user/password combination.

 

See https://github.com/edwig/ODBCQueryTool

Or https://sourceforge.net/projects/odbcquerytool/ for a ready installer

 

Hope this satisfies your needs.

 

Edwig Huisman
