### ISSUE TITLE
Way to open DSN/Connectionstring

### ISSUE THREAD

**Issue by hendrikp** [edwig/ODBCQueryTool#6]
Currently it seems one can only connect to predefined data sources, or i cant find the menu to just open a given Connectionstring without User/Password or some preselection.

e.g. i want to open this, and use the specified provider and not some other one:
```
Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\test.xlsx;Extended Properties='Excel 12.0 Xml;'
```

Is this currently possible?

**Comment by edwig** [comment]
Hello Hendrik,

 

No. This is currently not possible.

But you can register a wish on:  https://github.com/edwig/ODBCQueryTool/issues

And sometimes wishes come true…..

 

(And they most certainly do with the Open ODBC Querytool 😊 )

 

Best regards,

Edwig Huisman

 

From: Hendrik ***@***.***> 
Sent: dinsdag 18 april 2023 16:59
To: edwig/ODBCQueryTool ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [edwig/ODBCQueryTool] Way to open DSN/Connectionstring (Issue #6)

 

Currently it seems one can only connect to predefined data sources, or i cant find the menu to just open a given Connectionstring without User/Password or some preselection.

e.g. i want to open this, and use the specified provider and not some other one:

Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\test.xlsx;Extended Properties='Excel 12.0 Xml;'

Is this currently possible?

**Comment by edwig** [comment]
OK. Missed that you already did that. Now I must work harder to make it happen and make this post dissapear :-) :-)

**Comment by hendrikp** [comment]
No worry, it'd be still nice to have to analyze odbc/ole problems/issues.

I was mainly searching for a way to use it a dev-toool to explore a bit what is available through the provider/driver in regard if there's some hidden attributes on the views or tables. (but in this specific case it might not be even available what i search for, `tabSelected` attribute on worksheets(tables)/views in excel worksheets)

So far i haven't found another odbc/ole gui tool either, so maybe thats really a gap in the available oss toolsets still.
